### ISSUE TITLE
Crash while reading Mifare Ultralight C tags using ACR 122U reader

### ISSUE THREAD

**Issue by maskaravivek** [grundid/nfctools#31]
```
FATAL EXCEPTION: Thread-422
Process: in.zeta.android.pos.debug, PID: 11584
org.nfctools.NfcException: org.nfctools.NfcException: Unknown tag contents
at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:93)
at org.nfctools.mf.ul.Type2NfcTagListener.handleTag(Type2NfcTagListener.java:51)
at in.zeta.android.nfc.ReaderStateChangeListener.onStateChange(ReaderStateChangeListener.java:48)
at com.acs.smartcard.Reader$1.run(SourceFile:4097)
at java.lang.Thread.run(Thread.java:818)
Caused by: org.nfctools.NfcException: Unknown tag contents
at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:89)
```

**Comment by skjolber** [comment]
The tags might not contain Ndef data, so you should catch that execption and fall back to binary reading.

**Comment by Bubumuk** [comment]
@skjolber  
> catch that execption and fall back to binary reading.

Can you show me the way to binary reading?

**Comment by SuneethaYamani** [comment]
I am also facing same issue with mifare classic card.can you please share sample

**Comment by maskaravivek** [comment]
I wasn't able to figure out the issue using the library so i manually wrote/read the data page by page and then parsed it to read the actual messages.
