### ISSUE TITLE
Not working with NTAG215 cards

### ISSUE THREAD

**Issue by Fyb3roptik** [grundid/nfctools#32]
Getting this error:

```
10-16 23:18:52.001 2159-2187/eu.marcoalbarelli.android.usbtest E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: eu.marcoalbarelli.android.usbtest, PID: 2159
    org.nfctools.NfcException: org.nfctools.NfcException: Unknown memory size 62
        at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:96)
        at org.nfctools.mf.ul.Type2NfcTagListener.handleTag(Type2NfcTagListener.java:52)
        at eu.marcoalbarelli.android.usbtest.ReaderStateChangeListener.onStateChange(ReaderStateChangeListener.java:45)
        at com.acs.smartcard.Reader$a.run(SourceFile:846)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.nfctools.NfcException: Unknown memory size 62
        at org.nfctools.mf.ul.Type2NfcTagListener.createNdefOperations(Type2NfcTagListener.java:87)
        at org.nfctools.mf.ul.Type2NfcTagListener.handleTag(Type2NfcTagListener.java:52) 
        at eu.marcoalbarelli.android.usbtest.ReaderStateChangeListener.onStateChange(ReaderStateChangeListener.java:45) 
        at com.acs.smartcard.Reader$a.run(SourceFile:846) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by tontg** [comment]
Hi @Fyb3roptik,
This issue should be solved (sorry for the delay) in the ongoing [M9 branch](/grundid/nfctools/tree/M9). Support for NTAG 215 / 216 has been added. Don't hesitate to get back to me should there be any remaining issue.
